### ISSUE TITLE
Battery level not showing

### ISSUE THREAD

**Issue by Swiftnesses** [denniedegroot/com.ring#1]
Howdy!

I noticed the battery level on my Ring has never shown, can this be fixed?

Cheers,

Mark

**Comment by denniedegroot** [comment]
Sorry for the late response, I totally missed this issue. The battery level should be working. Are you using the Ring (non pro) version?

**Comment by Swiftnesses** [comment]
Yup, non pro... Not working here :(

**Comment by denniedegroot** [comment]
Did you remove and re-add the device after the 1.1.0 update? If not could you do this.

**Comment by Swiftnesses** [comment]
Tried to re-add it, no go, the motion and button work, battery doesn't :(

**Comment by denniedegroot** [comment]
As said on Slack I need a dump of the logging before I can fix this issue.

**Comment by denniedegroot** [comment]
No response from issuer

**Comment by Marcotics** [comment]
Ring doorbell 2 has shown a - as battery level since the day i bought it fairly recent

**Comment by paulvanderheijden90** [comment]
Ring 1 switchs to Ring 2 so ADD to the latest version. But no battery level.
