### ISSUE TITLE
Snapshot: Invalid_content_type

### ISSUE THREAD

**Issue by snurre66** [denniedegroot/com.ring#103]
Get an error showing Invalid_content_type when trying to grab a snapshot in homey.

![image](https://user-images.githubusercontent.com/48808867/184480291-bdb68cc4-e698-4d4f-a779-f4b5bf7760a6.png)

**Comment by dacootmeister** [comment]
Got the same error when inspecting snapshot

**Comment by Toon196** [comment]
Na laatste update geeft Homey Pro een foutmelding:

Authenticatie resultaat:
invalid_grant
Fout:
The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.

**Comment by daneedk** [comment]
@Toon196, There was an outage on the Ring API which most likely happend at the time Homey needed to refresh the authentication token. 
Please go to the devices settings, click **Maintenance** and use the **Try to Repair** function to reauthenticate.

(Also, please don't use the apps review section to post about errors. Would you please be so kind to change/remove your review, thanks.)

**Comment by Toon196** [comment]
It works again.
Thanks for the advise.
I removed the comment, sorry for that

Toon

Op do 6 okt. 2022 11:03 schreef Danee ***@***.***>:

**Comment by Sveinaeggen** [comment]
I have the same problem, I try to reauthenticate but no luck, I delete app and re install but still no change, same problem.

**Comment by snurre66** [comment]
My problem was resolved yesterday, after trying once more after 6months of not trying. 
I have had 2FA all this time.

Did the same yesterday as on previous attempts, but now it worked.

Maybe the stars was perfectly aligned, but probably some other reason I don't know.
