### ISSUE TITLE
App does not install on Homey V2 firmware

### ISSUE THREAD

**Issue by daneedk** [denniedegroot/com.ring#11]
Hi Dennie,

The app does not install on Homey V2 firmware because of the `"compatibility": "1.x >=1.5.0",` in app.json. I've changed it to `"compatibility": ">=1.5.0",` installed the app from the CLI and tested it with my Ring Pro and Ring Chime and all worked as expected. No errors in the CLI output, regular __refreshDevice_ and __https dings/active_. __syncDevices_ shows the correct Ring Pro and Ring Chime information so the app seems V2 ready to me. Could you please change the compatibility and publish the new version?

Many Thanks! Cheers,

Danee

**Comment by denniedegroot** [comment]
Hi Danee,

Thanks for letting me know. This issue will be resolved in the next version 2.0.4 which is waiting for approval.
