### ISSUE TITLE
Support for 2.0 (SDK2)

### ISSUE THREAD

**Issue by Fire69** [denniedegroot/com.ring#12]
Hi,

I came here to ask if the app would be updated to work on 2.0, but I saw in one of the other open issues you don't have a Ring anymore.
But I'm still going to try my luck :-P

I already tried installing it through CLI after changing compatibility in the json-file, it installs but you can't add a new device.
![screenshot_20181227-173536_homey gen 2](https://user-images.githubusercontent.com/1757287/50530414-6f310d00-0afd-11e9-8ef0-5d4930f51591.jpg)

**Comment by denniedegroot** [comment]
Yes this is normal behavior (also on 1.0). You need to go to the app settings and login.

**Comment by Fire69** [comment]
Wow, quick reply! :)

I'll try that tomorrow, still waiting for my Ring to be delivered.
Thanks!!

**Comment by denniedegroot** [comment]
How would you describe this sentence to make it more clear that you need to go to the app settings?

**Comment by Fire69** [comment]
I can confirm everything is working perfectly with 2.0!
Thanks for the support :)
