### ISSUE TITLE
'The generic alarm is turned on' listed twice

### ISSUE THREAD

**Issue by Fire69** [denniedegroot/com.ring#13]
![image](https://user-images.githubusercontent.com/1757287/50548694-ae707280-0c51-11e9-9989-6c3dd581f582.png)

I guess one of those should be 'Off' instead of 'On'.

**Comment by denniedegroot** [comment]
This is a translation error in Homey and not in the app. Please report this to Athom.

**Comment by Fire69** [comment]
I figured something like that, because I searched through all the files and couldn't find that specific sentence anywhere :)
Thanks, I'll report it to Athom 👍

**Comment by WeeJeWel** [comment]
Fixed in https://github.com/athombv/node-homey-lib/commit/e89dee15fcb6008411b939537ea7f27c0c4b03bb
