### ISSUE TITLE
Autorisation for Ring doesn't work

### ISSUE THREAD

**Issue by schaferrich** [denniedegroot/com.ring#16]
With my homey I tried to install the ring app so I can do something with it at Homey.
I filled in the autorisation, but or stille doesn't work.
Do you know how I can fix this?

**Comment by denniedegroot** [comment]
Is you authorization correct? Does the "revoke authorization" button appear?

**Comment by schaferrich** [comment]
Er verschijnt een grijze knop met de tekst:
'Verwijder autorisatie'
Is dat goed of juist niet?

**Comment by denniedegroot** [comment]
Ja dat zou goed moeten zijn. Heb je zojuist ook een log gestuurd? Daarin zie ik dat de verificatie niet lukt. Zou je de app eens kunnen verwijderen en opnieuw willen installeren?

**Comment by schaferrich** [comment]
Ik heb net week de apparaten toegevoegd van ring. Dus dat is wel gelukt...
Is dat dan voldoende?

**Comment by denniedegroot** [comment]
Als je apparaten kunt toevoegen is het gelukt. Wat is dan precies het probleem?

**Comment by schaferrich** [comment]
Ik dacht dat je in die app iets moest toevoegen, maar dat moest dus gewoon
via apparaten toevoegen...
Wat kun je verder doen met de app?

Mvg, Rich

Op zo 24 feb. 2019 12:37 schreef denniedegroot <notifications@github.com>:

**Comment by denniedegroot** [comment]
Of je deurbel, motion alarm afgaat en de chime laten afgaan bijv.
