### ISSUE TITLE
Feature request: Motion Alerts Toggle

### ISSUE THREAD

**Issue by 242Racing** [denniedegroot/com.ring#20]
Would it be possible to implement function to toggle "Motion alerts" on/off from Homey? Maybe this code can be used: 

https://github.com/tchellomello/python-ring-doorbell/issues/125

https://github.com/tchellomello/python-ring-doorbell/issues/126

**Comment by Airwolf33** [comment]
It would be great to be able to stop motion detection when we are at home !
Sure homey can do that :-)

**Comment by denniedegroot** [comment]
This should work, can someone confirm this?

**Comment by Airwolf33** [comment]
Hello,
I can’t test because I am no longer able to add my ring objects to Homey.
When I try to add my Stick up Cam or my doorbell, I got « Timeout after 30000ms » error.

Could you Help me ?

Regards,

Cedric

**Comment by denniedegroot** [comment]
@Airwolf33 are you using the laster git master version?

**Comment by Airwolf33** [comment]
I use v2.0.5 from Homey App Store.
How can I install the latest git master version ?

**Comment by denniedegroot** [comment]
https://community.athom.com/t/how-to-cli-install-method/198

**Comment by Airwolf33** [comment]
Motion detection is always On in my Ring app after running a Homey Flow to disable motion detection...

**Comment by AdyRock** [comment]
The new feature only works for Homey, so you can stop / start Homey reporting motion.
Each interface seems to have it's own setting so Homey can't change the Ring mobile app setting. This is the same with Alexa, the setting in there does not affect the Ring app and vice-versa.
Maybe you could switch the Ring app option off and just rely on Homey, that is what I have done.

**Comment by denniedegroot** [comment]
Released in the appstore.
