### ISSUE TITLE
Ring2 videodoorbel support wanted

### ISSUE THREAD

**Issue by Raycokes2000** [denniedegroot/com.ring#24]
Ring2 videodoorbel is not working unfortunately please add support
Regards Ray

**Comment by denniedegroot** [comment]
It is supported, what is not working?

**Comment by Gertje2105** [comment]
I also have a Ring Video doorbell 2. I want to make a flow:

**When** Ring is activated (doorbell is pushed) **Then** Send a Screenshot to my phone or something like that.

I think it is not possible now?

**Comment by mruiter** [comment]
Screenshot support from ring is broken atm 

Verstuurd vanaf mijn iPhone

**Comment by Raycokes2000** [comment]
Ring2 is not found to install, says no devices found.

**Comment by mruiter** [comment]
Strange in just re added a ring 2 without problems . Sign out and sign in youre cloud again in de ring app settings try again 

Verstuurd vanaf mijn iPhone

**Comment by Raycokes2000** [comment]
Aha got it, probably user privelige issue. Ring has several users eg different owner/user. Meaning could be blocked vor normal users. I now haveused owner username 👌👍
