### ISSUE TITLE
Cant log in

### ISSUE THREAD

**Issue by follox** [denniedegroot/com.ring#25]
When trying to add my login details I am getting this error:
Error: invalid_authentication 401 {"error":"access_denied","error_description":"invalid user credentials"}

Any help would be much appreciated.

**Comment by denniedegroot** [comment]
Are you sure you are using the right account details? If not are you the "master" user of the Ring app?

**Comment by follox** [comment]
I figure out that I had to manually write my credentials instead of using the autofill on my phone. If you use that it gives me that error.
