### ISSUE TITLE
Image url catching and maybee pushing 2 homey image var

### ISSUE THREAD

**Issue by mruiter** [denniedegroot/com.ring#3]
The API image info has now been "hacked" into the unoffical API support
Would it be possible to expand the app to support these new available api commands

Like image/movie url to variable or even push the image to the homey image var for other apps ?

**Comment by denniedegroot** [comment]
Do you have a link where you found this integration? The only thing I can do is grabbing the video url, but not an image.

**Comment by denniedegroot** [comment]
No response from issuer
