### ISSUE TITLE
ring video doorbell / stick up camera report no movements

### ISSUE THREAD

**Issue by delor001** [denniedegroot/com.ring#34]
since the update of Homey I have had problems with the rinp app. I had created a flow that reported movements of the front door (ring video door bell) through speech through homey. this no longer works, I would also have created a flow when the doorbell rings, it still works. Also movements that the stick up camera detects are no longer mentioned. I do get notifications from the ring app. From ring on my tablet. I had approached the people of Homey, but these refer me to the developer of the app.

ps. I have already made new flows and restarted Homey but this did not help.

Regards,
Peter

**Comment by AdyRock** [comment]
I have the same problem. I have installed the latest version (2.1.4) via the CLI and that has fixed the recent issue where nothing was reported so I now get button press notifications.
I do see in the console log for the '_syncDevices { doorbots:' the field 'subscribed_motions: false,' which is suspicious. I can't see anyway to change that as it is switched on in the Ring app and in the Alex app and they report motion. My Samsung smartthings app also reports movement.

I have tried removing the device and adding it back and restarted the app before and after replacing it.
Do you know if there is an API command to switch it on?

**Comment by AdyRock** [comment]
After writing the above I saw another issue about switching the motion off and on so I used the example that pointed to and added the following to Api.js:

```
    enableMotion (device_data, callback) {
        console.log('enableMotion', device_data);

        this._https('POST', '/doorbots/' + device_data.id + '/motions_subscribe', null, true, (error, result) => {
            callback(error, result);
        });
    }
```
then to app.js:

```
    enableMotion(data, callback) {
        this._api.enableMotion(data, callback);
    }
```

and finally to device.js at the end of _initDevice():

>         let _this = this;
>         let device_data = this.getData();
> 
>         return new Promise(function(resolve, reject) {
>             Homey.app.enableMotion(device_data, (error, result) => {
>             });
>         });

Now I get motion alerts. So that fixed my problem and verifies the suggested code works. Maybe something like this could be added to the official code

**Comment by mruiter** [comment]
Did you try a remove the ring device and add it again this solved that problem at one of my sites 

Verstuurd vanaf mijn iPhone

**Comment by AdyRock** [comment]
Yes, I tried that first but it didn't help. I even tried revoking my account and signed in again and then added the device. 

The only fix for me was to add the changes that enabled the notification.

**Comment by delor001** [comment]
hi,
will there be a new app for this change? my knowledge is not sufficient to put this in the app o.i.d. to adjust.

Regards,
Peter

Verstuurd vanaf mijn iPad

**Comment by denniedegroot** [comment]
I will have a look into the enabling/disabling motion.

**Comment by denniedegroot** [comment]
Enalbing/disabling motion should work with my latest commit, can someone confirm this?

**Comment by AdyRock** [comment]
Yes, it does indeed work, nice one.

**Comment by denniedegroot** [comment]
Released in the appstore.
