### ISSUE TITLE
Ring not working in Homey 3.0

### ISSUE THREAD

**Issue by Pim65** [denniedegroot/com.ring#35]
Hi Dennie,

It seems that the ring app is giving problems in Homey after updating to 3.0
Testing a flow manually works, but if the trigger comes from the doorbell it is not.

Is this something known or can it be solved?

THNX Pim

**Comment by evroekel** [comment]
+1 same issue here. 

Also issue with two day authentication. I do get a SMS-code after sharing credentials with the app but no place to add the code in the app.

**Comment by mruiter** [comment]
Working perfect on 7 different homeys here no trouble at all on 3 , 3.1 and 3.2 series firmware

Two factor authentication isn’t supported . You should turn it off if you want to use anything else then the official ring app

Verstuurd vanaf mijn iPhone

**Comment by Pim65** [comment]
Sorry, Working after a small update.
