### ISSUE TITLE
Error: too many requests from dependency service & authentication issue

### ISSUE THREAD

**Issue by evroekel** [denniedegroot/com.ring#36]
![IMG_5523](https://user-images.githubusercontent.com/57673156/68770538-9a91ed00-0626-11ea-8450-4676c19194f9.jpeg)

I got two questions:
1. Any idea what this (image above) means and how to solve this? 
2. After entering my credentials I do get a authentication code from ring a couple of minutes later. But no place to add this in the ring form.

Homey version: 3.0.0
App version: 3.1.0.429
Homey Ring app: v2.0.5

**Comment by mruiter** [comment]
You need to disable 2fac authentication it’s not supported in app

Verstuurd vanaf mijn iPhone

**Comment by evroekel** [comment]
Thx.. That solved the issue, but I'll open a new issue cards are not available in the homey flow :-(
