### ISSUE TITLE
kan niet autoriseren in homey

### ISSUE THREAD

**Issue by nicofr1908** [denniedegroot/com.ring#4]
goede morgen,

ik krijg steeds de melding error:invalid_authentication 401 you need to sign in or up before continuing

mijn inlog gegevens kloppen

heeft u een idee?

mvg

Nico kloos

**Comment by nicofr1908** [comment]
iemand een idee??

**Comment by denniedegroot** [comment]
Heb je de laatste versie geprobeerd? Dit zou namelijk opgelost moeten zijn in 2.0.1.

**Comment by fresam** [comment]
Hi,

I also have the same problem as AntonK1 above when I try to install my new Video Ringbell 2 and Spotlight Cam Battery. First same error message:

Error: invalid_authentication 401 {"error":"unauthorized_client","error_description":"The client is not authorized to request a token using this method."}

When trying again no message/response at all. Tried to reinstall the app a couple of times but still the same issue.
Running Ring version 2.0.1

**Comment by denniedegroot** [comment]
Ring changed something in their API again.....ugh

**Comment by AntonK1** [comment]
Hoi Dennie,

Bedankt voor je reactie. Waardeloos dat Ring de API blijft veranderen. Bugs herstellen of zaken toevoegen kan ik me wat bij voorstellen.

Ga jij de gewijzigde Api (in Homey) nu aanpassen of? Hoor graag van je.

Gr. Anton Klunder

Verstuurd vanaf mijn iPhone

**Comment by denniedegroot** [comment]
Update is al naar de app store gestuurd. Nu wachten op goedkeuring voordat ik hem kan uitrollen.

**Comment by fresam** [comment]
Thanks for the quick response and solution. I will wait for the new version on appstore.

**Comment by AntonK1** [comment]
Thanks! The 2.0.2 version works fine for me also within flows etc.

Gr. Anton Klunder

**Comment by denniedegroot** [comment]
Fixed in 2.0.2
