### ISSUE TITLE
Stickup cam - motion detection only works when motion alerts are activated in Ring app

### ISSUE THREAD

**Issue by FrankSmeets01** [denniedegroot/com.ring#42]
I'm trying the Homey Ring app for the first time (v2.1.4 on Homey V3.2.0). I notice that Homey only detects motion from the Stickup Cam when the motion alerts are set to ON in the native Ring app. When turned OFF, Homey doesn't detect any motion. Even when I activate motion detection via the action card. By reading https://github.com/denniedegroot/com.ring/issues/20, I expected it to be working independently from the alert-settings in the native Ring-app.

I also have a Doorbell Pro and this one works as expected. Homey detects any motion, indepently from the setting in the native Ring app on my phone.

Hope this can be fixed!

**Comment by FrankSmeets01** [comment]
Can please be looked into this issue (different behavior of the Stickup Cam compared to the Doorbell Pro).

**Comment by FrankSmeets01** [comment]
I found some direction on the issue that I raised. I'm using a 'motion schedule' on my Stick-up Cam. When this rules disables the motion alerts it apparently overrules the motion-alert in the API that is triggering Homey.
Can it be checked whether this is due to a bug in the homey-ring app? Or whether this is caused by a bug/feature (:-) from the Ring API?

**Comment by denniedegroot** [comment]
This is a limitation of the Ring API. It is not possible for me to change/implement this.
