### ISSUE TITLE
Motion on/off does not work

### ISSUE THREAD

**Issue by jeesnl** [denniedegroot/com.ring#43]
To set the motion detection on or off Via a flow does not work for the stick up cam.

**Comment by dwillemsen** [comment]
I am having the same issue. I can't set the motion detection on the stick up camera. It says that the device is not found

**Comment by Munnikie** [comment]
I have the same problem. But my problem, it does not say that the device is not found. It just does not enable/disable motion detection.

**Comment by Munnikie** [comment]
@denniedegroot I can see that some issues are open for a while now. Are you still committed to this repository?

**Comment by PortoNL** [comment]
Bump! I'm Having this issue aswell.

**Comment by tokreutz** [comment]
Having the same problem

**Comment by tokreutz** [comment]
I am working on a fix for this. Not sure about what device «kinds» are affected by this though. My stickup cam (battery) is of kind «cocoa_camera» and is not working. I know how to fix it for this kind, but I don’t have devices to confirm for any other types.

What cams does every one else on the thread have? Battery, wired, etc.?
