### ISSUE TITLE
Ring doorbell makes two-factor verification mandatory!

### ISSUE THREAD

**Issue by evroekel** [denniedegroot/com.ring#47]
https://www.bbc.com/news/technology-51555450

BBC: "Ring doorbell makes two-factor verification mandatory"

While this app says "Two-Factor Security Authentication is not supported, you must disable this on your Ring account!" So end of story? I hope not...

**Comment by Allram** [comment]
Duplicate of #46

**Comment by denniedegroot** [comment]
Duplicate
