### ISSUE TITLE
Kan niet authorisere

### ISSUE THREAD

**Issue by Aklijzing** [denniedegroot/com.ring#5]
Hi!
Na de installatie en nadat ik mijn inloggegevens heb ingevuld krijg ik de melding:

Before Homey can add Ring products we need authentication.

Enig idee hoe verder?

**Comment by mruiter** [comment]
Do you have pop up blocker turned off in Chrome ?

Verstuurd vanaf mijn iPhone

**Comment by Aklijzing** [comment]
tried this put no pop up started....

**Comment by denniedegroot** [comment]
Are you authenticated in the Ring settings?

**Comment by Aklijzing** [comment]
Despite I received this message I am able to add the Ring now!

**Comment by denniedegroot** [comment]
Solved
