### ISSUE TITLE
Losing authentication v2.2.0 (2FA edition)

### ISSUE THREAD

**Issue by Genghes** [denniedegroot/com.ring#51]
Hi.
Installed and running the 2.2.0 version. (@kaohlive version ;)  #46 )
The authentication works fine, but after a couple of minutes/ hours the authentication drops.
A restart of the app works as a workaround.

Here is a exerpt from the log when this happens:

_refreshDevice
_https /dings/active
2020-03-09 17:43:43 [log] [ManagerDrivers] [doorbell] [0] _syncDevice []
_refreshDevice
_https /dings/active
2020-03-09 17:43:48 [log] [ManagerDrivers] [doorbell] [0] _syncDevice []
_refreshDevice
_https /dings/active
2020-03-09 17:43:53 [log] [ManagerDrivers] [doorbell] [0] _syncDevice []
_refreshDevices
_https /ring_devices
_https : invalid_authentication :  401 {"error":"Unauthorized", "status_code":401}
_refreshDevice
_https /dings/active
_https : not_authenticated
_refreshDevice
_https /dings/active
_https : not_authenticated
_refreshDevice
_https /dings/active
_https : not_authenticated

**Comment by kaohlive** [comment]
make sure you get the latest version from dennies version. this issue was present in my first pull but it should be fixed a day later.
i have been running it now for a week without any reauthorization requirements.

**Comment by Genghes** [comment]
Ahh.. 
Thats how it goes when I test and forget to check for newer releases.

Just checked ant the 2.2.2 version is Live on Athom.
So I will install that on my production Homey.

**Comment by Genghes** [comment]
Closing Issue, Probably fixed. No need to keep this ticket open.

**Comment by Patrick1610** [comment]
I do keep having this problem with the 2.2.2 version.. The app does say it's authenticated, but when I test I flow I get an error.. 
![image](https://user-images.githubusercontent.com/6585375/76699819-5f292d00-66b1-11ea-9043-b2f73c87c074.png)
<img width="625" alt="Screenshot 2020-03-15 at 11 36 29" src="https://user-images.githubusercontent.com/6585375/76699826-68b29500-66b1-11ea-8fee-da8fac325eeb.png">

**Comment by kaohlive** [comment]
If you try to add a new device, what do you get then? does it end with no devices available or with an error?

**Comment by Patrick1610** [comment]
I have already added al my devices successfully, so now I get the ‘No new devices found’ text.

**Comment by kaohlive** [comment]
but that means the authentication still works. Else you would get an error there.
So its amother problem I am afraid. Image grabbing unique maybe. Do you get generic alarms when the bell has been used? or do they also fail

**Comment by Patrick1610** [comment]
No I don’t get generic alarms, nor do I get motion alarms. Basically, only the device adding works..

**Comment by kaohlive** [comment]
so you have mfa enabled and while authorizing you received your token and submitted it. then you add you devices and the first few hours it works, but later you get unauthorized in the grab image (easy to test instead of alarms). Alarms no longer work either. Re-authorization enables working again for a few hours.
after these hours you still can complete the add device wizard. 

good summary?

**Comment by Patrick1610** [comment]
Perfect summary! The ‘add device wizard’ was enough to reauthenticate and get everything working for a while (even grabber). 

Any idea what could be the cause of the problem?

**Comment by kaohlive** [comment]
no, not if you are using the app version from the homey store and not my first fork. Sounds exact the issue i fixed later on and is in the 2.2.2 version.
very strange. there is a timer that checks and refreshes now, before it was after app restart and device adding. 
the device adding wizard did not ask you to reauthenticate?

**Comment by Patrick1610** [comment]
Yes, I am. I have never installed a fork or anything. I had the previous app. Installed this one and uninstalled that one. Later I even uninstalled the 2.2.2 and reinstalled to check if that fixed the problem :( 

Each time I entered the device wizard it asked for authentication

**Comment by kaohlive** [comment]
then you are loising the refresh token indeed. very strange.

**Comment by Patrick1610** [comment]
I have just tried adding a new device again, and it didn’t ask for authentication again, so it seems to work :)

**Comment by kaohlive** [comment]
ok lets keep track, see if it gets lost again.

**Comment by Raycokes2000** [comment]
i hoped v2.2.2 2fa would work properly, but it still does not, there is no input field for the code sent unfortunately

**Comment by kaohlive** [comment]
so you revoked the auth in app settings? then went into add device, select ring, a device type and got the new authentication page. enter credentials, press login, get a code entry box enter the just received code into the box and authorize. but you do not get the code box in that step?

**Comment by kaohlive** [comment]
posys crossed, you wouldn't see a new device if you still have all devices registered, that is not bad. it should work from that point also on those devices. if you removed your r devices from homey you should see them at the end of the wizard. else something went wrong during login.

**Comment by Raycokes2000** [comment]
could not even revoke, older version was not auto updated, so did this myself, then got 2 version, so now cleaning up. old flow gone, app gone, reboot homey. now going blank with this app again.
looked like cluster fuck app with app versions.

**Comment by Raycokes2000** [comment]
still nothing unfortunatley, after 2fa code, says no new device found

**Comment by kaohlive** [comment]
if you can generate a log and send it i coupd take a look. if you go through the add device wizard again, do you have to authorize again or does that step get skipped now?

**Comment by Raycokes2000** [comment]
authorize is skipped, allready approved, yoy see shortly that screen then skips and says no new devices found
76a44799-f2cc-43eb-9b0a-0c8d27448069
what does it need to say at apps ring, settings,  my ring authorise here says, error you need to authenticte from add device wizard!

**Comment by kaohlive** [comment]
so the add device wizard is acting like its properly authorized but you are missing a device that is not present in your homey yet. sinse no device just suggest all your device are added to homey already. without the log i can not help you determine why you are missing devices OR that homey thinks they are already registered (maybe from the old dubble app) but its not an mfa issue as far as i xan tell. maybe best to open a new issue for this one. but i would check the e homey dev screen first and list your registered devices there. ensure your ring device is not there already

**Comment by Raycokes2000** [comment]
ok, but you need logging now? whee is extra logging for you available, you have diag report, and a new issue?

**Comment by Raycokes2000** [comment]
in there a way to remove authorisation? can not see that now

**Comment by kaohlive** [comment]
i am not the app publisher so i get no logs when you send them, not sure how you can share them now. 
you should be able to revoke in the app settings. but you stated that screen tells you its not authorized. so something weird is still going on in your deployment. on what homey version are you?

**Comment by Patrick1610** [comment]
> ok lets keep track, see if it gets lost again.

Well, unfortunately the connection is lost again.. :(

**Comment by Raycokes2000** [comment]
@kaohlive sorry for delay, v2.2.2

**Comment by Raycokes2000** [comment]
after several reboots, revoked authorisation, but stil after adding nothing happened. is shared user accepted of doet is need to be admin user required? i rather not use such account in homey

**Comment by Genghes** [comment]
For your information.
I have used the v2.2.2 for several weeks and it works perfectly.
Tried it om two homeys, Pro and Standard.

I Have given it my only Ring login, not a shared, but I dont think that should be an issue.

Be aware that if you have disabled Motion or Ring alerts in the Ring app they will not register in Homey app as well.
(If you hav snoozed or by schedule in Ring app the same goes for Homey.)

Try enabeling ALL in the Ring app.

Also be aware Ring has TWO different 2FA. One they just forced on everyone and one you can enable in the account.
You have to Enable 2FA in the Ring Account (Even if Ring forced it on your account)

And the account: It's no problem giving the app the Admin account. The app that account just to get a token and then use the token when connecting after that.
I don't think the password is stored in Homey anyway. Correct me if I'm wrong @kaohlive @denniedegroot

**Comment by kaohlive** [comment]
i am also using my admin account. And you are correct we only store the refresh token and keep the temo access token in memory and no account info is stored at all.

**Comment by Genghes** [comment]
I also had problems when Ring forced 2FA. But loggin in to Ring.com I saw 2FA NOT ENABLED.
So even if they have forced 2FA on it is NOT ON when you veiw your account information.

After logging in to Ring.com (with 2FA) ?!? and then enabeling 2FA everything worked.

**Comment by kaohlive** [comment]
Hi @Genghes , @Patrick1610. @Raycokes2000 , I think I identified when this fails. In case of the grabimage and its receives a not found error the code threats this as a failed authentication reason. Tries to refresh and still gets an error, than it marks the app as unauthenticated.
Ill make some code to handle this scenario as a not found for the grabsnaphot action.

**Comment by kaohlive** [comment]
Just commited a fix (I think) in my fork. Ill create a new pull request for @denniedegroot 
All I did was add a check on 404 to still give an error to the flow card but with resource not found instead of invalid credentials and it does not invalidate the authentication as a next step.

**Comment by Patrick1610** [comment]
> Hi @Genghes , @Patrick1610. @Raycokes2000 , I think I identified when this fails. In case of the grabimage and its receives a not found error the code threats this as a failed authentication reason. Tries to refresh and still gets an error, than it marks the app as unauthenticated.
> Ill make some code to handle this scenario as a not found for the grabsnaphot action.

Amazing you found and fixed the problem!! Just curious, what could be the cause that no snapshot can be grabbed, if the connection/authentication is solid?

**Comment by kaohlive** [comment]
what i understand from that api its not a trigger to make a snapshot, it just downloads the most recent one after checking for a fresh one. maybe that check should trigger the device to make one not sure. but today it suddenly started to give a 404 on my device, but during debugging those dissapeared again. So it may be something as silly as ring restarting a service or something. or how often you use your live view. no real idea.

**Comment by Raycokes2000** [comment]
2fa is no problem here anymore, rebooted several times and used admin account/main user accont and now it works but 2.2.3 is not workingen properly my flow do not work after this update

**Comment by kaohlive** [comment]
what 2.2.3 version did you take, the one from the test link or from github and installed using cli?
i see no reason why your flows might have stopped, some people reported that ring disabled alerts. check to see those are active please
