### ISSUE TITLE
New snapshot view

### ISSUE THREAD

**Issue by AdyRock** [denniedegroot/com.ring#54]
I see the place for the new snapshot in the device but it is not refreshing. This maybe that it's not supported for the Ring Pro doorbell.
If it could be made to work that would be great.

**Comment by AdyRock** [comment]
Ah, I see the displayed image is the one captured by the flow command.
Could it be refreshed by the refresh control like the IP cameras do?

**Comment by kaohlive** [comment]
Just comitted a new fork that does this actually

**Comment by kaohlive** [comment]
@denniedegroot check out the new pull request. It holds a refactor on the camera image code and replaces some deprecated code with current ones.

@AdyRock to make things a bit more relative, it does not tell the camera to make a new snapshot, just refreshes the latest snapshot uploaded by the camera. The grabimage action did that also, so no workaround there.

**Comment by denniedegroot** [comment]
Merged. I think this ticket can be closed?
