### ISSUE TITLE
Geen connectie tussen Homey en ring alarmsysteem

### ISSUE THREAD

**Issue by marcel-1984** [denniedegroot/com.ring#71]
Beste,

Kan er gekeken worden of het ring alarm
Systeem toegevoegd kan worden aan de ring app in de Homey applicatie? Dit zou heel fijn zijn.

**Comment by mruiter** [comment]
Ik weet dat ring connecties naar ring deurbellen “ gedoogd.
Ze doen er niet geheimzinnig over dat niet gecertificeerde connecties zoals de honey app naar ring security/alarm via hun api direct met een ban worden beloond .

Logische ook vóór een alarm systeem dat bepaalde certificaten heeft voor veiligheid.

Je kan iig via ifttt de koppeling maken . Kan je gewoon beide synchroon laten lopen .

Of gewoon de ring ditchen . Homey en je router op ups en knallen . Berichtje sms , notificatie of een voip call als je niet bij een alarm centrale aangesloten zit .

Heb je kpn hutsefluts abbo kan je nog gratis of voor 2,50 per maand een 4g backup krijgen (of gewoon zelf regelen) en je hebt een beter systeem dan ring .

De kans is aannemelijk dat binnenkort de andere ring devices zoals deur sensor en pir misschien ook we direct met honey the pairen zijn bij de aankomende firmware releases van homeyos 

Verstuurd vanaf mijn iPhone
