### ISSUE TITLE
Feature request: Please add taking snapshot

### ISSUE THREAD

**Issue by gruijter** [denniedegroot/com.ring#9]
It is possible to take a snapshot from ring. Could you make an action card that does just this? That would really be a killer application since I refuse to pay 3 euro's per month for cloud recording :)

See this link for snapshot implementation for ring in python:
https://github.com/tchellomello/python-ring-doorbell/pull/108

**Comment by denniedegroot** [comment]
And where is this snapshot then stored? This will be an 'action flow card' so how would the action card look to you on Homey?

**Comment by gruijter** [comment]
The snapshot is taken with an action card. The resulting image will then start a trigger card with the image as token. Similar to what image grabber is doing: https://apps.athom.com/app/image.grabber

**Comment by denniedegroot** [comment]
Ah ok, that should be possible. Are you willing to test/debug the support for this as I don't have any Ring devices anymore?

**Comment by mruiter** [comment]
Also willing to test, can even give full access to the homey if wanted

**Comment by mruiter** [comment]
The new Ring App gives a snapshot on the app screen and refreshes once in a while or when movement (i think) These pictures should be available somewhere .
That in combination with the movement alert could become something like.
1. Movement -> then ->  Put latest snapshot from ring api in tag 
2. when tag image blabla changes -> telegram image blabla tag

**Comment by gruijter** [comment]
Exactly, this is how it works also on android. The link I provided to the python implentation contains the endpoint / information how to retrieve snapshots

**Comment by rodroz** [comment]
Also willing to test image grabbing. Would like a image tag to be used in conjunction with ie Telegram.

**Comment by gruijter** [comment]
Any news on this feature request?

**Comment by denniedegroot** [comment]
I really can't integrate it without having a device. The only other possibility is that someone shares their Ring account so I can access the devices, but this is of course "privacy" sensitive.

**Comment by gruijter** [comment]
Maybe someone with a ring is willing to take over the maintenance of the Homey app?

**Comment by denniedegroot** [comment]
They can always make a pull request.

**Comment by mruiter** [comment]
Geen probleem!

Verstuurd vanaf mijn Apple Watch

Op 2 mrt. 2019 om 01:42 heeft denniedegroot <notifications@github.com> het volgende geschreven:

**Comment by mruiter** [comment]
Dennie I can send my credentials on slack if you want access to a ring .

Just be aware I sleepwalk at night .... nude or in clown 🤡 costume 

Verstuurd vanaf mijn iPhone

**Comment by denniedegroot** [comment]
I created a new branch named 'image_grab'. The trigger works and has the jpg data from Ring, but it doesn't seem to work for me...

**Comment by denniedegroot** [comment]
Now it works for me, please test it and let me know. Also test the ring Chime if you can.

**Comment by rodroz** [comment]
Hi, 

you actually able to grab the image from ring ? .. When will this be implemented in the ring app on Homey ?.. :)

**Comment by mruiter** [comment]
Soooooon 

Verstuurd vanaf mijn iPhone

**Comment by rodroz** [comment]
That's is excellent, an donation is coming your way when updated. Thank you.

**Comment by gruijter** [comment]
Tested and got it working eventually with https://apps.athom.com/app/email.sender to send the snapshot by email on motion detection.

Good job @denniedegroot !

**Comment by mruiter** [comment]
Telegram also works 

Verstuurd vanaf mijn iPhone

**Comment by denniedegroot** [comment]
A beta version is submitted to the App store. If there are any issues please create a new ticket.

**Comment by rodroz** [comment]
Downloaded the beta and tried a flow. Just getting invalid authentication 404 when using the grab image card. Is there anything that I missed?

**Comment by rodroz** [comment]
Hmm just started working without the error.. Ok, now to see how to send the grabbed image to telegram

**Comment by mruiter** [comment]
Use the a new snapshot card from ring as trigger and telegram app send image as action card.
Use the image tag that’s available for the telegram action card 

Verstuurd vanaf mijn iPhone

**Comment by denniedegroot** [comment]
@rodroz use the image tag in the ‘if’ flow card.

**Comment by rodroz** [comment]
Thanks Dennie, I managed to make 2 flows. One for grabbing and one for sending. Excellent work.

**Comment by rodroz** [comment]
Haha, getting the samme image over and over... Any ideas for that?

**Comment by denniedegroot** [comment]
Could you create a new issue for that?
